// Code generated by suave/gen. DO NOT EDIT.
// Hash: 4a10f3a7693ab926db2ea93f06f8c3f82fd6b44c4803dc6c99e5b707e5da3982
package types

import "github.com/ethereum/go-ethereum/common"

type BidId [16]byte

// Structs

type Bid struct {
	Id                  BidId
	Salt                BidId
	DecryptionCondition uint64
	AllowedPeekers      []common.Address
	AllowedStores       []common.Address
	Version             string
}

type BuildBlockArgs struct {
	Slot           uint64
	ProposerPubkey []byte
	Parent         common.Hash
	Timestamp      uint64
	FeeRecipient   common.Address
	GasLimit       uint64
	Random         common.Hash
	Withdrawals    []*Withdrawal
	Extra          []byte
}

type IASResponseBody struct {
	Id                    string
	Timestamp             string
	Version               string
	IsvEnclaveQuoteStatus string
	IsvEnclaveQuoteBody   string
	EpidPseudonym         string
	AdvisoryURL           string
	AdvisoryIDs           string
}

type IASResponseHeader struct {
	RequestID                    string
	XIASReportSignature          string
	XIASReportSigningCertificate string
	Date                         string
}

type Withdrawal struct {
	Index     uint64
	Validator uint64
	Address   common.Address
	Amount    uint64
}
